//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acomptefournisseur
    {
        public int idAcompteFournisseur { get; set; }
        public string banque { get; set; }
        public string date { get; set; }
        public string dateEcheance { get; set; }
        public Nullable<bool> encaisse { get; set; }
        public string modePayment { get; set; }
        public Nullable<float> montant { get; set; }
        public string numChequeTraite { get; set; }
        public string proprietaire { get; set; }
        public Nullable<int> FOURNISSEUR_idPersonne { get; set; }
    
        public virtual personne personne { get; set; }
    }
}
