//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresse
    {
        public adresse()
        {
            this.personnes = new HashSet<personne>();
        }
    
        public int idAdresse { get; set; }
        public string codePostal { get; set; }
        public string gouvernorat { get; set; }
        public string rue { get; set; }
        public string ville { get; set; }
    
        public virtual ICollection<personne> personnes { get; set; }
    }
}
