//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ajt_photo
    {
        public int id_photo { get; set; }
        public string id_user_fk { get; set; }
        public byte[] image { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
    }
}
