//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public article()
        {
            this.bonentrees = new HashSet<bonentree>();
        }
    
        public int idArticle { get; set; }
        public Nullable<bool> aBonEntree { get; set; }
        public string dateArticle { get; set; }
        public Nullable<float> montantHT { get; set; }
        public Nullable<float> montantTTC { get; set; }
        public Nullable<float> prixAchatHT { get; set; }
        public Nullable<float> prixVenteHT { get; set; }
        public Nullable<float> prixVenteTTC { get; set; }
        public Nullable<float> quantite { get; set; }
        public string refPaquet { get; set; }
        public Nullable<float> remise { get; set; }
        public string unite { get; set; }
        public string CATEGORIE_refCategorie { get; set; }
        public Nullable<int> CHOIX_ID { get; set; }
        public Nullable<int> FOURNISSEUR_idPersonne { get; set; }
        public Nullable<int> MARQUE_ID { get; set; }
        public string REFARTICLE_refArticle { get; set; }
        public Nullable<int> SITE_ID { get; set; }
        public string SOUSCATEGORIE_refSousCategorie { get; set; }
    
        public virtual categorie categorie { get; set; }
        public virtual choix choix { get; set; }
        public virtual personne personne { get; set; }
        public virtual marque marque { get; set; }
        public virtual referencearticle referencearticle { get; set; }
        public virtual site site { get; set; }
        public virtual souscategorie souscategorie { get; set; }
        public virtual ICollection<bonentree> bonentrees { get; set; }
    }
}
