//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class articlesachete
    {
        public articlesachete()
        {
            this.lougueurs = new HashSet<lougueur>();
            this.bons = new HashSet<bon>();
        }
    
        public int id { get; set; }
        public Nullable<float> NBREPIECES { get; set; }
        public Nullable<float> PUHT { get; set; }
        public Nullable<float> QUANTITE { get; set; }
        public Nullable<float> REMISE { get; set; }
        public string CATEGORIE_refCategorie { get; set; }
        public Nullable<int> CHOIX_ID { get; set; }
        public Nullable<int> MARQUE_ID { get; set; }
        public string REFARTICLE_refArticle { get; set; }
        public string SOUSCATEGORIE_refSousCategorie { get; set; }
        public Nullable<int> UNITE_ID { get; set; }
    
        public virtual categorie categorie { get; set; }
        public virtual choix choix { get; set; }
        public virtual marque marque { get; set; }
        public virtual referencearticle referencearticle { get; set; }
        public virtual souscategorie souscategorie { get; set; }
        public virtual unite unite { get; set; }
        public virtual ICollection<lougueur> lougueurs { get; set; }
        public virtual ICollection<bon> bons { get; set; }
    }
}
