//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class encaissementclient
    {
        public encaissementclient()
        {
            this.acomptes = new HashSet<acompte>();
            this.personnes = new HashSet<personne>();
        }
    
        public int ID { get; set; }
        public string NUMEC { get; set; }
        public Nullable<int> BON_ID { get; set; }
    
        public virtual bon bon { get; set; }
        public virtual ICollection<acompte> acomptes { get; set; }
        public virtual ICollection<personne> personnes { get; set; }
    }
}
