//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lougueur
    {
        public lougueur()
        {
            this.articlesachetes = new HashSet<articlesachete>();
        }
    
        public int idLongueur { get; set; }
        public Nullable<float> longueur { get; set; }
        public Nullable<int> nbrePieces { get; set; }
        public Nullable<float> totalLongueur { get; set; }
    
        public virtual ICollection<articlesachete> articlesachetes { get; set; }
    }
}
