//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdsocofebEntities1 : DbContext
    {
        public bdsocofebEntities1()
            : base("name=bdsocofebEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acompte> acomptes { get; set; }
        public virtual DbSet<acomptefournisseur> acomptefournisseurs { get; set; }
        public virtual DbSet<acomptepersonnel> acomptepersonnels { get; set; }
        public virtual DbSet<adresse> adresses { get; set; }
        public virtual DbSet<ajt_collaborator> ajt_collaborator { get; set; }
        public virtual DbSet<ajt_photo> ajt_photo { get; set; }
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<articlesachete> articlesachetes { get; set; }
        public virtual DbSet<aspnetrole> aspnetroles { get; set; }
        public virtual DbSet<aspnetuserclaim> aspnetuserclaims { get; set; }
        public virtual DbSet<aspnetuserlogin> aspnetuserlogins { get; set; }
        public virtual DbSet<aspnetuser> aspnetusers { get; set; }
        public virtual DbSet<aspnetusersext> aspnetusersexts { get; set; }
        public virtual DbSet<banque> banques { get; set; }
        public virtual DbSet<bon> bons { get; set; }
        public virtual DbSet<bonentree> bonentrees { get; set; }
        public virtual DbSet<categorie> categories { get; set; }
        public virtual DbSet<choix> choixes { get; set; }
        public virtual DbSet<encaissementclient> encaissementclients { get; set; }
        public virtual DbSet<lougueur> lougueurs { get; set; }
        public virtual DbSet<marque> marques { get; set; }
        public virtual DbSet<modepayement> modepayements { get; set; }
        public virtual DbSet<my_aspnet_applications> my_aspnet_applications { get; set; }
        public virtual DbSet<my_aspnet_membership> my_aspnet_membership { get; set; }
        public virtual DbSet<my_aspnet_paths> my_aspnet_paths { get; set; }
        public virtual DbSet<my_aspnet_personalizationallusers> my_aspnet_personalizationallusers { get; set; }
        public virtual DbSet<my_aspnet_personalizationperuser> my_aspnet_personalizationperuser { get; set; }
        public virtual DbSet<my_aspnet_profiles> my_aspnet_profiles { get; set; }
        public virtual DbSet<my_aspnet_roles> my_aspnet_roles { get; set; }
        public virtual DbSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup { get; set; }
        public virtual DbSet<my_aspnet_sessions> my_aspnet_sessions { get; set; }
        public virtual DbSet<my_aspnet_sitemap> my_aspnet_sitemap { get; set; }
        public virtual DbSet<my_aspnet_users> my_aspnet_users { get; set; }
        public virtual DbSet<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
        public virtual DbSet<mysql_membership> mysql_membership { get; set; }
        public virtual DbSet<personne> personnes { get; set; }
        public virtual DbSet<personne_modepayement> personne_modepayement { get; set; }
        public virtual DbSet<personnel> personnels { get; set; }
        public virtual DbSet<referencearticle> referencearticles { get; set; }
        public virtual DbSet<referencebon> referencebons { get; set; }
        public virtual DbSet<sequence> sequences { get; set; }
        public virtual DbSet<site> sites { get; set; }
        public virtual DbSet<souscategorie> souscategories { get; set; }
        public virtual DbSet<stockvariant> stockvariants { get; set; }
        public virtual DbSet<taxe> taxes { get; set; }
        public virtual DbSet<unite> unites { get; set; }
        public virtual DbSet<mysql_roles> mysql_roles { get; set; }
        public virtual DbSet<mysql_usersinroles> mysql_usersinroles { get; set; }
    }
}
