//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class personne_modepayement
    {
        public int Client_idPersonne { get; set; }
        public int payementClients_IDMODEPAYEMENT { get; set; }
        public int Fournisseur_idPersonne { get; set; }
    
        public virtual modepayement modepayement { get; set; }
        public virtual personne personne { get; set; }
        public virtual personne personne1 { get; set; }
    }
}
