//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        public site()
        {
            this.articles = new HashSet<article>();
        }
    
        public int ID { get; set; }
        public string CODESITE { get; set; }
        public string EMPLACEMENT { get; set; }
    
        public virtual ICollection<article> articles { get; set; }
    }
}
