//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockvariant
    {
        public int idStockVariant { get; set; }
        public Nullable<float> puht { get; set; }
        public Nullable<float> stockActuel { get; set; }
        public Nullable<float> stockLivre { get; set; }
        public string CATEGORIE_refCategorie { get; set; }
        public Nullable<int> CHOIX_ID { get; set; }
        public Nullable<int> FOURNISSEUR_idPersonne { get; set; }
        public Nullable<int> MARQUE_ID { get; set; }
        public string REFERENCEARTICLE_refArticle { get; set; }
        public string SOUSCATEGORIE_refSousCategorie { get; set; }
    
        public virtual categorie categorie { get; set; }
        public virtual choix choix { get; set; }
        public virtual marque marque { get; set; }
        public virtual personne personne { get; set; }
        public virtual referencearticle referencearticle { get; set; }
        public virtual souscategorie souscategorie { get; set; }
    }
}
