//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bois.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class unite
    {
        public unite()
        {
            this.articlesachetes = new HashSet<articlesachete>();
        }
    
        public int ID { get; set; }
        public string CODEUNITE { get; set; }
        public string LIBELLEUNITE { get; set; }
    
        public virtual ICollection<articlesachete> articlesachetes { get; set; }
    }
}
